### ISSUE TITLE
Repo Ownership

### ISSUE THREAD

**Issue by daykin** [epicsdeb/epics-debhelper#12]
Now that NSLS-II is off of Debian, We (FRIB) would like to adopt this repository. @aderbenev is this acceptable to you?

**Comment by aderbenev** [comment]
At this time we at NSLS-II don't have facilities to build/package/publish for Debian. It makes sense to pass the baton to someone who can do that. This would probably go beyond just the `epics-debhelper` repo as `epicsdeb` contains 'debianization' for many EPICS modules and the base. We stopped with the most prominent packages [somewhere around Deb10](https://epicsdeb.bnl.gov/debian/buster.html).

@mdavidsaver @ralphlange thoughts?

**Comment by mdavidsaver** [comment]
No objections from me.

@daykin Who all do you have in mind, and at what level of permission?

**Comment by ralphlange** [comment]
I'm making @daykin co-owner, replacing @mark0n. I think that's appropriate, given that FRIB probably has the only remaining Debian package factory based on this packaging.
